name: Build RC

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.102
    - name: Install dependencies
      run: dotnet restore src/ASPNET.CQRS.csproj
        && dotnet restore tests/ASPNET.CQRS.Tests.csproj
        && dotnet restore example/ASPNET.CQRS.Example.csproj
    - name: Build
      run: dotnet build src/ASPNET.CQRS.csproj --configuration Debug --no-restore
    - name: Test
      run: dotnet test tests/ASPNET.CQRS.Tests.csproj --no-restore --verbosity normal
